const SURVEY_DESCRIPTION_LENGTH = 1000;
const SURVEY_TITLE_LENGTH = 250;
const SURVEY_QUESTION_LENGTH = 1000;
const SURVEY_ANSWER_LENGTH = 250;

export {
  SURVEY_DESCRIPTION_LENGTH,
  SURVEY_TITLE_LENGTH,
  SURVEY_QUESTION_LENGTH,
  SURVEY_ANSWER_LENGTH
};
