service: your-voice-posts-api
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-auto-swagger
  - serverless-dynamodb
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  # lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  timeout: 30 

custom:
  dynamodb:
    stages:
      - dev
    start:
      # docker: true
      port: 8000
      inMemory: false
      migrate: true
      sharedDb: true
      seed: true
      # noStart: true
    seed:
      domain:
        sources:
          - table: ${env:CHALLENGES_TABLE}
            rawsources: [../data_source/stg-Challenges.json]
          - table: ${env:COMMENTS_TABLE}
            rawsources: [../data_source/stg-Comments.json]
          - table: ${env:FOLLOWERS_TABLE}
            rawsources: [../data_source/stg-Followers.json]
          - table: ${env:FEEDS_TABLE}
            rawsources: [../data_source/stg-Feeds.json]
          - table: ${env:NOTIFICATIONS_TABLE}
            rawsources: [../data_source/stg-Notifications.json]
          - table: ${env:MP_POSTS_TABLE}
            rawsources: [../data_source/stg-MPPosts.json]
          - table: ${env:POSTS_TABLE}
            rawsources: [../data_source/stg-Posts.json]
          - table: ${env:VOTES_TABLE}
            rawsources: [../data_source/stg-Votes.json]
          - table: ${env:USER_TABLE}
            rawsources: [../data_source/stg-User.json]
      

  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - "aws-sdk"
    target: "node16"
    define:
      require.resolve: "undefined"
    platform: "node"
    concurrency: 10

  # userPoolArn: ${env:AWS_USER_POOL_ARN}

  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

  userPoolArn: ${env:AWS_USER_POOL_ARN}

  autoswagger:
    title: "Post API Documentation"
    apiType: "http"
    generateSwaggerOnDeploy: true
    typefiles: ["./src/types/post.d.ts"]
    schemes: ["https"]
    host: "vax5qqh64a.execute-api.ap-southeast-2.amazonaws.com"
    basePath: "/${opt:stage}"
    apiKeyHeaders: ["Authorization"]

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:PutItem"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - { "Fn::GetAtt": ["aus_geocodes", "Arn"] }
            - { "Fn::GetAtt": ["User", "Arn"] }
            - { "Fn::GetAtt": ["InvitedMP", "Arn"] }
            - { "Fn::GetAtt": ["Posts", "Arn"] }
            - { "Fn::GetAtt": ["Followers", "Arn"] }

functions: ${file(src/serverless/functions.yml)}

resources: ${file(src/serverless/dynamodb.yml)}
